Join game api
Game-as-a-Service/game-mystic-elven-mines-nx pull request #14
Opened 2023-07-19 15:12 UTC by Jacky0428

**此次內容：**
新增 Join Game API

---
**Issue：**
- resolve #7

2023-07-20 01:36 UTC, Wally5077 requested changes
**Review done.**

2023-07-20 01:36 UTC, Wally5077 commented on packages/backend/app/src/main/java/tw/waterballsa/gaas/saboteur/app/usecases/JoinGameUsecase.java
> +        SaboteurGame saboteurGame = saboteurGameRepository.findById(gameId).orElseThrow();
這裡應該讓 Optional 幫忙拋 **NotFoundException**，不能直接 **orElseThrow()**

2023-07-20 01:36 UTC, Wally5077 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurController.java
> +    }
Q：為什麼這支 API 也是新增的 ?

2023-07-20 01:36 UTC, Wally5077 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurController.java
> +    public JoinGameViewModel joinGame(@PathVariable String gameId, @RequestBody JoinGameRequest request) {
參數換行

2023-07-20 01:36 UTC, Wally5077 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurController.java
> +    }
沒有要驗證參數的話，使用 **JoinGameUsecase.Request** 就可以了

2023-07-20 01:36 UTC, Wally5077 commented on packages/backend/spring/src/test/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurGameControllerTest.java
> +            .andExpect(jsonPath("$.players[1].name").value("BB"));
也要驗證 Player B 的 id 是否存在

2023-07-20 02:17 UTC, Jacky0428 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurController.java
> +    }
程式碼方法的順序不太對
上次的 ticket，不小心把 findGame() 放到 playCard() 下方
這次順手換了一下位子

2023-07-20 15:22 UTC, Jacky0428 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurController.java
> +    public JoinGameViewModel joinGame(@PathVariable String gameId, @RequestBody JoinGameRequest request) {
fixed

2023-07-20 15:23 UTC, Jacky0428 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurController.java
> +    }
fixed. 驗證必須給 name 參數，createGame 也順便驗證了

2023-07-20 15:23 UTC, Jacky0428 commented on packages/backend/spring/src/test/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurGameControllerTest.java
> +            .andExpect(jsonPath("$.players[1].name").value("BB"));
fixed

2023-07-23 14:29 UTC, Wally5077 requested changes
**Review done.**

2023-07-23 14:29 UTC, Wally5077 commented on packages/backend/app/src/main/java/tw/waterballsa/gaas/saboteur/app/usecases/JoinGameUsecase.java
> +    public void execute(String gameId, Request request, Presenter presenter) {
`gameId` 放進 `Request`

2023-07-23 14:29 UTC, Wally5077 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/advices/SaboteurAdvice.java
> +    }
不需要，框架會做

2023-07-23 14:29 UTC, Wally5077 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurController.java
> +                .filter(StringUtils::isNotBlank).findFirst()
`findFirst` 換行

2023-07-23 14:29 UTC, Wally5077 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurController.java
> +                .orElseThrow(() -> new IllegalRequestException("Host name is required"));
用 Spring validation 做，讓全局例外處理 Spring validation 的例外就好，不用自己開 `IllegalRequestException`

2023-07-23 14:29 UTC, Wally5077 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurController.java
> +                .orElseThrow(() -> new IllegalRequestException("Host name is required"));
ditto `IllegalRequestException`

2023-07-23 14:29 UTC, Wally5077 commented on packages/backend/domain/src/main/java/tw/waterballsa/gaas/saboteur/domain/exceptions/IllegalRequestException.java
> +    }
這不需要

2023-07-24 15:39 UTC, Jacky0428 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurController.java
> +                .filter(StringUtils::isNotBlank).findFirst()
fixed

2023-07-24 15:39 UTC, Jacky0428 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurController.java
> +                .orElseThrow(() -> new IllegalRequestException("Host name is required"));
fixed

2023-07-24 15:39 UTC, Jacky0428 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/controllers/SaboteurController.java
> +                .orElseThrow(() -> new IllegalRequestException("Host name is required"));
fixed

2023-07-24 15:39 UTC, Jacky0428 commented on packages/backend/domain/src/main/java/tw/waterballsa/gaas/saboteur/domain/exceptions/IllegalRequestException.java
> +    }
fixed

2023-07-24 15:44 UTC, Jacky0428 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/saboteur/spring/advices/SaboteurAdvice.java
> +    }
框架預設回傳一堆資訊的 json，但我們希望只回傳 message 即可

2023-07-24 15:46 UTC, Jacky0428 commented
fix done.

2023-07-24 16:07 UTC, Jacky0428 commented
fix done.

2023-07-25 14:37 UTC, Wally5077 submitted a review, later dismissed
**LGTM**

2023-07-28 13:24 UTC, Wally5077 approved these changes
**LGTM**

2023-07-28 13:24 UTC, Wally5077 commented on packages/backend/spring/pom.xml
> +            <version>1.6.12</version>
這不能直接用 Spring 的配置，而是一定要自己定義 Version 嗎

2023-07-28 13:32 UTC, Jacky0428 commented on packages/backend/spring/pom.xml
> +            <version>1.6.12</version>
對，Spring 好像沒有配置這個的 version

2023-07-29 02:30 UTC, merged