遊戲開始 & 玩家公開資訊的 API
Game-as-a-Service/game-mystic-elven-mines-nx pull request #27
Opened 2023-09-30 08:28 UTC by Jacky0428

**此次內容：**
1. 新增遊戲開始 API
2. 新增玩家公開資訊 API

---
**Issue：**
- resolve #23

2023-09-30 12:04 UTC, Wally5077 requested changes
**Review done.**

2023-09-30 15:37 UTC, Jacky0428 commented on packages/backend/spring/src/test/java/com/gaas/mystic/elven/controllers/ElvenGameControllerTest.java
> +    public void testPlayerFindPlayersInfoBeforeGameStarted() throws Exception {
這支測試其實是之前 Story 01 寫的
當初是要測試可以看到所有玩家的資訊
測試內容只要保證有玩家名稱就好

不過現在 Story 03 遊戲開始後，也會需要看到玩家資訊的 API
除了玩家名字之外，還需要看到手牌數量和工具狀態
目前打算直接沿用之前的 API 即可
測試內容就是下面的 `testPlayerFindPlayersInfoAfterGameStarted`

因此
上面這支 API 只改了方法名，加入`BeforeGameStarted`強調遊戲開始前
和改了 url ，加入 players 強調是玩家的資訊

下面這支 API 是新的測試，加入`AfterGameStarted`強調遊戲開始後
並且測試是否有名字、手牌數量、工具狀態

2023-09-30 15:37 UTC, Jacky0428 commented on packages/backend/spring/src/test/java/com/gaas/mystic/elven/controllers/ElvenGameControllerTest.java
> +    public void testPlayerFindPlayersInfoAfterGameStarted() throws Exception {
上方已說明

2023-10-01 13:26 UTC, Wally5077 approved these changes
**LGTM**

2023-10-01 13:26 UTC, frankvicky approved these changes

2023-10-01 14:54 UTC, merged