first version
Game-as-a-Service/game-mystic-elven-mines-nx pull request #29
Opened 2023-10-24 14:35 UTC by Jacky0428

2023-10-27 08:19 UTC, Wally5077 commented on packages/backend/domain/src/main/java/com/gaas/mystic/elven/domain/card/FixCard.java
> +    public final String name = "FixCard";
1. CardType 可以放在父類
2. 為什麼需要 public？
3. **"FixCard"** 其實就是 **FixCard.class.getSimpleName()**
4. 如果其他卡牌類也有相關的作法，可以一併調整

2023-10-27 08:21 UTC, Wally5077 commented on packages/backend/domain/src/main/java/com/gaas/mystic/elven/domain/card/MapCard.java
> +    public final String name = "MapCard";
ditto 卡牌類

2023-10-27 08:21 UTC, Wally5077 commented on packages/backend/domain/src/main/java/com/gaas/mystic/elven/domain/card/RockFallCard.java
> +    public final String name = "RockFallCard";
ditto 卡牌類

2023-10-27 08:24 UTC, Wally5077 commented on packages/backend/domain/src/main/java/com/gaas/mystic/elven/domain/role/RoleCard.java
> +        return valueOf(name);
1. name 為 null，應屬於非法操作，可以直接丟例外出去
2. 這邊建議 Enum.values() + stream，去取得第一個與 enum 名字一樣的 enum (不分大小寫)，找不到就拋例外

2023-10-27 08:27 UTC, Wally5077 commented on packages/backend/spring/src/main/java/com/gaas/mystic/elven/repositories/data/DeckData.java
> +    }
不用這個類別，你只需要在 ElvenGameData 取得所有 CardData 後，直接轉換成 Card 再創建 Deck 就好了

2023-10-27 08:30 UTC, Wally5077 commented on packages/backend/spring/src/test/java/com/gaas/mystic/elven/repositories/data/ElvenGameDataTest.java
> +                        CardData.toData(new RockFallCard())), "GOBLIN")
別給字串，直接給 enum

2023-10-30 14:13 UTC, Jacky0428 commented on packages/backend/domain/src/main/java/com/gaas/mystic/elven/domain/role/RoleCard.java
> +        return valueOf(name);
name 為 null，是有可能的情況，在遊戲還沒開始或還沒抽角色卡之前，玩家 RoldCard 應該為 null

2023-10-30 14:13 UTC, Jacky0428 commented on packages/backend/spring/src/main/java/com/gaas/mystic/elven/repositories/data/PlayerData.java
> +        var role = Optional.ofNullable(player.getRoleCard()).map(RoleCard::name).orElse(null);
name 為 null，是有可能的情況，在遊戲還沒開始或還沒抽角色卡之前，玩家 RoldCard 應該為 null

2023-10-30 14:15 UTC, Jacky0428 commented
已修正

2023-10-30 16:47 UTC, Wally5077 requested changes
**Review done.**

2023-10-30 16:47 UTC, Wally5077 commented on packages/backend/domain/src/main/java/com/gaas/mystic/elven/domain/card/Card.java
> +    String getName();
你可以將這改成抽象類，並將這倆方法變成抽象類屬性

2023-10-30 16:47 UTC, Wally5077 commented on packages/backend/spring/src/main/java/com/gaas/mystic/elven/presenters/views/CardView.java
> +            .build();
兩個屬性可以直接用「全參建構子」

2023-10-30 16:47 UTC, Wally5077 commented on packages/backend/spring/src/test/java/com/gaas/mystic/elven/repositories/data/ElvenGameDataTest.java
> +                        CardData.toData(new RockFallCard())), RoleCard.GOBLIN.name())
這邊不要給字串

2023-10-30 16:47 UTC, Wally5077 commented on packages/backend/spring/src/main/java/com/gaas/mystic/elven/repositories/data/PlayerData.java
> +        var role = Optional.ofNullable(player.getRoleCard()).map(RoleCard::name).orElse(null);
那這邊也不要給字串，要給就給 Enum

2023-11-11 16:08 UTC, merged